version: 2.1

jobs:
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - run:
          name: Deploy Environment Variables to EC2
          command: |
            ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $USER@$DNS '
            # Create a temporary file to store updated environment variables
            temp_env=$(mktemp)

            # Function to update environment variables
            update_env_var() {
              local var_name="$1"
              local var_value="$2"
              
              # Only process if value is not empty
              if [ -n "$var_value" ]; then
                # Copy existing /etc/environment to the temp file
                cp /etc/environment "$temp_env"

                # Remove the variable from the temp file if it exists
                sed -i "/^${var_name}=/d" "$temp_env"
                
                # Append the new variable
                echo "${var_name}=${var_value}" >> "$temp_env"
                
                # Safely replace the original environment file
                sudo mv "$temp_env" /etc/environment
              else
                echo "Warning: ${var_name} is empty. Skipping."
              fi
            }

            # Application Variables
            update_env_var "PORT" "${PORT}"
            update_env_var "CLIENT_URL" "${CLIENT_URL}"
            update_env_var "DB" "${DB}"
            update_env_var "JWT_SECRET" "${JWT_SECRET}"
            update_env_var "EMAIL" "${EMAIL}"
            update_env_var "PASS" "${PASS}"

            # AWS Credentials
            update_env_var "AWS_ACCESS_KEY_ID" "${AWS_ACCESS_KEY_ID}"
            update_env_var "AWS_SECRET_ACCESS_KEY" "${AWS_SECRET_ACCESS_KEY}"
            update_env_var "S3_REGION" "${S3_REGION}"
            update_env_var "S3_BUCKET" "${S3_BUCKET}"

            # Verify the additions
            echo "Updated /etc/environment:"
            cat /etc/environment
            '

      - run:
          name: Execute Deployment Script
          command: |
            ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $USER@$DNS '
            # Load updated environment variables
            source /etc/environment

            # Append custom paths to PATH if necessary
            export PATH=$PATH:/home/ubuntu/.npm-global/bin

            # Execute the deployment script
            ./deploy.sh
            '

workflows:
  deploy-to-ec2:
    jobs:
      - deploy
