version: 2.1

jobs:
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - run:
          name: Deploy Environment Variables to EC2
          command: |
            ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $USER@$DNS '
            # Function to add environment variables with safety checks
            add_env_var() {
              local var_name="$1"
              local var_value="$2"
              
              # Only add if value is not empty
              if [ -n "$var_value" ]; then
                # Remove existing entries for this variable
                sudo sed -i "/$var_name=/d" /etc/environment
                
                # Add the new variable
                echo "$var_name=$var_value" | sudo tee -a /etc/environment
              else
                echo "Warning: $var_name is empty. Skipping."
              fi
            }

            # Application Variables
            add_env_var "PORT" "${PORT}"
            add_env_var "CLIENT_URL" "${CLIENT_URL}"
            add_env_var "DB" "${DB}"
            add_env_var "JWT_SECRET" "${JWT_SECRET}"
            add_env_var "EMAIL" "${EMAIL}"
            add_env_var "PASS" "${PASS}"

            # AWS Credentials
            add_env_var "AWS_ACCESS_KEY_ID" "${AWS_ACCESS_KEY_ID}"
            add_env_var "AWS_SECRET_ACCESS_KEY" "${AWS_SECRET_ACCESS_KEY}"
            add_env_var "S3_REGION" "${S3_REGION}"
            add_env_var "S3_BUCKET" "${S3_BUCKET}"

            # Verify the additions
            echo "Updated /etc/environment:"
            cat /etc/environment
            '

      - run:
          name: Execute Deployment Script
          command: |
            ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $USER@$DNS '
            export PATH=$PATH:/home/ubuntu/.npm-global/bin
            ./deploy.sh
            '

workflows:
  deploy-to-ec2:
    jobs:
      - deploy
