version: 2.1

jobs:
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    environment:
      USER: ${USER}
      DNS: ${DNS}
      SAGAR: ${SAGAR}
    steps:
      - run:
          name: Deploy to EC2
          command: ssh -oStrictHostKeyChecking=no -v $USER@$DNS "./deploy.sh"

workflows:
  deploy-to-ec2:
    jobs:
      - deploy
